[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Railway automatically injects environment variables from dashboard
# No need to specify them here - Railway handles this automatically
# The Dockerfile CMD instruction handles the startup command
